#!/usr/bin/env python3
"""tools/gni_blocks.py -- GENERATOR for GNI ARCHITECTURE section 5 (BUILDING BLOCK VIEW).

Born S100. Scope is SECTION 5 ONLY.

THE BOUNDARY, restated from the one DECISION S99-1 drew, because a generator that does not
know its own edge grows into the next section's territory:
  section 5 = what is WRITTEN     -- source: the AST of every tracked *.py
  section 6 = what ACTUALLY RAN   -- source: GitHub Actions run history  (S99)
  section 7 = what is DECLARED    -- source: .github/workflows/*.yml + `gh secret list`  (S94)

SECTION 5 DOES NOT PARSE WORKFLOWS. "Nothing in the tree imports this module" is a claim the
AST can make exactly. "No workflow invokes it" is section 7.1's entrypoint column, already
generated by `tools/gni_state.py`. The join between the two tables is the reader's, and both
halves stay true. Section 6 made the opposite call for its cron regex and wrote its reason
down; this is the same discipline reaching the other answer, for a different reason: the
missing half here is ALREADY GENERATED next door, so copying it would create a second
opinion, not a second source (R-S96-3).

WHY THERE IS NO HARVEST STEP. Section 6 split harvest from render because its evidence lived
on GitHub's servers and moved every thirty minutes, so a git-tracked snapshot was the only
way to make "unchanged tree -> identical output" true. Section 5's evidence IS the tree. A
snapshot here would add a file that can drift from the source it claims to describe, which is
the failure this whole roadmap row exists to remove.

NO CLOCK IS RENDERED INTO THE OUTPUT. `tools/gni_state.py` puts `datetime.now()` inside its
generated stamp and therefore fails roadmap 2's completion test on its own account -- two runs
two seconds apart differ (item 5.33, measured S99). The stamp below carries the INPUT's
identity instead: HEAD, the file count, and an EOL-normalised md5 over the source manifest.

THE WORD "DEAD" IS NOT USED. An AST cannot see `getattr`, string dispatch, a CLI entry, or a
name exported through `__all__`. The unsafe direction for a dead-code claim is calling
something dead while it is alive, so every such column reads NO STATIC REFERENCE FOUND and
section 5.6 lists what the instrument cannot see. R-S99-1 applied before the fact.

R-S93-1: the instrument checks its own expectations BY THE SCRIPT, against synthetic sources
with known answers, before it reads one real file. R-S98-6: every matcher is probed against a
case it must CATCH and a case it must MISS.

R-S81-5 / C5: no expected value published below is hand-written. Counts are counted.

FILE DECODING IS utf-8-sig ON PURPOSE. Six files under `ai_engine/` carry a BOM; decoding as
plain utf-8 leaves U+FEFF at the head of the text and `ast.parse` fails on it. This is not a
guess -- `tools/gni_rule_checks.py` documented it at its own line 66 after being bitten.

IMPORTABLE ON PURPOSE. `collect`, `analyse`, `render` and `norm_md5` are module-level so that
a future staleness check can call THIS tool's parser rather than write a second one. That is
the precedent C6 set when it imported `gni_macro_map.parse_rules` instead of re-implementing
it (R-S96-3). No such check exists yet; the item is filed, not silently skipped.

Usage:
    python tools/gni_blocks.py --session 100            # -> docs/GNI_ARCHITECTURE_S100.md
    python tools/gni_blocks.py --session 100 --stdout   # print section 5, write nothing
Exit codes: 0 ok - 2 the INSTRUMENT refused (bad args, control probe, unparseable source)
            3 an input is missing.
"""

from __future__ import annotations

import argparse
import ast
import hashlib
import re
import subprocess
import sys
from pathlib import Path

if hasattr(sys.stdout, "reconfigure"):          # item 5.22: cp1252 consoles kill the run
    sys.stdout.reconfigure(encoding="utf-8", errors="replace")
    sys.stderr.reconfigure(encoding="utf-8", errors="replace")

HERE = Path(__file__).resolve().parent
ROOT = HERE.parent                  # derived from HERE: the working directory does not matter
DOCS = ROOT / "docs"

DUNDER_RE = re.compile(r"^__.*__$")


# --------------------------------------------------------------------------- io

def norm_md5(raw: bytes) -> str:
    """R-S98-3: hash what the content IS, not how git handed it over."""
    if raw.startswith(b"\xef\xbb\xbf"):
        raw = raw[3:]
    return hashlib.md5(raw.replace(b"\r\n", b"\n")).hexdigest()


def decode(raw: bytes) -> str:
    """utf-8-sig: six files under ai_engine/ carry a BOM and ast.parse dies on it."""
    return raw.decode("utf-8-sig", "replace")


def sh(args: list[str], cwd: Path | None = None) -> tuple[int, str]:
    try:
        p = subprocess.run(args, cwd=str(cwd or ROOT), capture_output=True, text=True,
                           encoding="utf-8", errors="replace", timeout=120)
        return p.returncode, p.stdout or ""
    except Exception as exc:                                       # noqa: BLE001
        return 1, "<%s: %s>" % (type(exc).__name__, exc)


def tracked_py(root: Path) -> list[Path]:
    """Tracked *.py only. `git ls-files` is deterministic on an unchanged tree, and it
    excludes the venv, build output and anything untracked -- none of which is architecture."""
    rc, out = sh(["git", "ls-files", "*.py"], cwd=root)
    if rc != 0:
        return []
    return [root / line.strip() for line in out.splitlines() if line.strip()]


# --------------------------------------------------------------------------- naming

def sys_path_sites(tree: ast.AST) -> int:
    """Count `sys.path.append(...)` / `sys.path.insert(...)` calls.

    These are why a module has more than one name. `ai_engine/mad_runner.py` does
    `sys.path.append(dirname(__file__))`, which makes `ai_engine/` a path root, so its
    siblings address each other as `from quota_guard import ...` and its subpackages as
    `from analysis.mad_protocol import ...` -- never as `ai_engine.quota_guard`. A resolver
    that knows only the package-relative name matches NONE of those and reports an almost
    edgeless graph. That is exactly what this generator's first run did."""
    n = 0
    for node in ast.walk(tree):
        if isinstance(node, ast.Call) and isinstance(node.func, ast.Attribute) \
                and node.func.attr in ("append", "insert") \
                and isinstance(node.func.value, ast.Attribute) \
                and node.func.value.attr == "path" \
                and isinstance(node.func.value.value, ast.Name) \
                and node.func.value.value.id == "sys":
            n += 1
    return n


def aliases_of(path: Path, roots: list[Path]) -> set[str]:
    """Every dotted name this file answers to, one per path root it sits under.

    Roots are DERIVED, not listed: the repo root, plus every directory holding a tracked
    `*.py`, because Python puts the entry script's own directory on `sys.path` and this tree
    additionally appends parents by hand. `ai_engine/analysis/mad_protocol.py` therefore
    answers to `ai_engine.analysis.mad_protocol`, `analysis.mad_protocol` AND `mad_protocol`,
    and which one a given import uses depends on who is running."""
    out: set[str] = set()
    for r in roots:
        try:
            rel = path.relative_to(r)
        except ValueError:
            continue
        parts = list(rel.parts)
        if parts[-1] == "__init__.py":
            parts = parts[:-1]
        else:
            parts[-1] = parts[-1][:-3]
        if parts:
            out.add(".".join(parts))
    return out


def module_name(path: Path, root: Path) -> str:
    """Dotted module name, derived by walking up while __init__.py exists.

    ai_engine/analysis/foo.py -> ai_engine.analysis.foo   (ai_engine/ is a package)
    tools/gni_state.py        -> gni_state                (tools/ is not)
    dryrun_x.py               -> dryrun_x
    """
    rel = path.relative_to(root)
    parts = list(rel.parts)
    stem = parts[-1][:-3] if parts[-1].endswith(".py") else parts[-1]
    pkg: list[str] = []
    d = path.parent
    while d != root and (d / "__init__.py").is_file():
        pkg.insert(0, d.name)
        d = d.parent
    if stem == "__init__":
        return ".".join(pkg) if pkg else "__init__"
    return ".".join(pkg + [stem])


# --------------------------------------------------------------------------- ast

def imports_of(tree: ast.AST) -> tuple[list[list[str]], set[str]]:
    """Return (chains, relative_forms).

    Each BINDING produces one CHAIN of candidate dotted names, longest first. The caller
    resolves a chain to AT MOST ONE edge -- the longest candidate that names a real module.

    Chains, not a pooled set, because pooling loses which candidate came from which
    statement: `from pkg import alpha` would then yield edges to BOTH `pkg` and `pkg.alpha`,
    every package `__init__.py` would look heavily imported, and no package could ever appear
    as unreferenced. The control probe caught exactly that on this file's first run.

    `from X import y` is genuinely ambiguous in the AST -- `y` may be a submodule or a symbol
    -- so the chain is [X.y, X] and the real module set decides, which is the only thing that
    can. `relative_forms` holds any `from .x import y`; this tree contains none today, and if
    one ever appears the caller REFUSES rather than resolving it wrongly.
    """
    chains: list[list[str]] = []
    relative: set[str] = set()
    for node in ast.walk(tree):
        if isinstance(node, ast.Import):
            for a in node.names:
                parts = a.name.split(".")
                chains.append([".".join(parts[:i]) for i in range(len(parts), 0, -1)])
        elif isinstance(node, ast.ImportFrom):
            if node.level:
                relative.add("." * node.level + (node.module or ""))
                continue
            if not node.module:
                continue
            for a in node.names:
                chains.append([node.module + "." + a.name, node.module])
    return chains, relative


def module_symbols(tree: ast.Module) -> set[str]:
    """Module-level definitions only: def, async def, class, and plain NAME = ... .
    Underscore names are KEPT -- `_FORCE_PROVIDER` is precisely the class of symbol this
    section exists to surface. Dunders are kept too and flagged at render time."""
    out: set[str] = set()
    for node in tree.body:
        if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef, ast.ClassDef)):
            out.add(node.name)
        elif isinstance(node, ast.Assign):
            for t in node.targets:
                if isinstance(t, ast.Name):
                    out.add(t.id)
        elif isinstance(node, ast.AnnAssign) and isinstance(node.target, ast.Name):
            out.add(node.target.id)
    return out


def referenced_names(tree: ast.AST) -> set[str]:
    """Every name READ and every attribute label read anywhere in the module.

    LOAD CONTEXT ONLY. `_FORCE_PROVIDER = None` creates an ast.Name for the target in STORE
    context, and counting that as a reference would make every constant look used by its own
    definition -- which silently empties the one table this section exists to fill.

    Attributes are included because `mod.SYMBOL` is how a symbol crosses a module boundary.
    This over-collects across modules on purpose: a false NEGATIVE for dead code is the safe
    direction, and the over-collection is disclosed in 5.6."""
    out: set[str] = set()
    for node in ast.walk(tree):
        if isinstance(node, ast.Name) and isinstance(node.ctx, ast.Load):
            out.add(node.id)
        elif isinstance(node, ast.Attribute) and isinstance(node.ctx, ast.Load):
            out.add(node.attr)
    return out


# --------------------------------------------------------------------------- collect

def collect(root: Path) -> dict:
    """Parse every tracked *.py once. Raises ValueError -- never returns a partial map --
    when a source will not parse or two files claim one module name."""
    paths = tracked_py(root)
    if not paths:
        raise ValueError("`git ls-files '*.py'` returned nothing under %s" % root)
    roots = sorted({root} | {p.parent for p in paths}, key=lambda p: len(p.parts))
    mods: dict[str, dict] = {}
    clashes: list[str] = []
    manifest: list[str] = []
    for path in sorted(paths):
        if not path.is_file():
            raise ValueError("tracked but absent from the working tree: %s" % path)
        raw = path.read_bytes()
        name = module_name(path, root)
        try:
            tree = ast.parse(decode(raw), filename=str(path))
        except SyntaxError as exc:
            raise ValueError("%s will not parse: %s" % (path, exc))
        if name in mods:
            clashes.append("%s claimed by %s and %s"
                           % (name, mods[name]["rel"], path.relative_to(root).as_posix()))
            continue
        chains, rel_forms = imports_of(tree)
        mods[name] = {
            "rel": path.relative_to(root).as_posix(),
            "chains": chains,
            "relative": rel_forms,
            "symbols": module_symbols(tree),
            "refs": referenced_names(tree),
            "aliases": aliases_of(path, roots),
            "path_sites": sys_path_sites(tree),
        }
        manifest.append("%s\0%s" % (path.relative_to(root).as_posix(), norm_md5(raw)))
    if clashes:
        raise ValueError("module name collision -- " + "; ".join(sorted(clashes)))
    rc, head = sh(["git", "rev-parse", "--short", "HEAD"], cwd=root)
    return {
        "modules": mods,
        "roots": [r.relative_to(root).as_posix() or "." for r in roots],
        "head": head.strip() or "unknown",
        "manifest_md5": norm_md5(("\n".join(sorted(manifest)) + "\n").encode("utf-8")),
    }


# --------------------------------------------------------------------------- analyse

def resolve(target: str, known: set[str]) -> str | None:
    """Longest-prefix resolution of an import target against the real module set.
    `ai_engine.analysis.foo.bar` resolves to `ai_engine.analysis.foo` when that module
    exists. A target matching nothing is EXTERNAL -- stdlib or third party -- and this
    function deliberately does not try to say which: distinguishing them needs a
    hand-written list, and a hand-written list is the thing C5 forbids."""
    parts = target.split(".")
    for i in range(len(parts), 0, -1):
        cand = ".".join(parts[:i])
        if cand in known:
            return cand
    return None


def analyse(snap: dict) -> dict:
    """Everything published is derived here. No threshold is hand-written."""
    mods = snap["modules"]
    known = set(mods)
    if not known:
        raise ValueError("no module survived collection")

    stray = {n: sorted(v["relative"]) for n, v in mods.items() if v["relative"]}
    if stray:
        raise ValueError(
            "relative imports found and this resolver does not handle them: "
            + "; ".join("%s -> %s" % (n, ",".join(f)) for n, f in sorted(stray.items())))

    # ALIAS MAP. A name may be claimed by more than one file once the tree's own path roots
    # are taken into account. An ambiguous alias produces NO edge and is COUNTED, because a
    # coin-flip between two real modules is worse than a gap that says so.
    alias_map: dict[str, set[str]] = {}
    for name, v in mods.items():
        for al in v["aliases"]:
            alias_map.setdefault(al, set()).add(name)
    ambiguous = {al: sorted(owners) for al, owners in alias_map.items() if len(owners) > 1}

    edges: dict[str, set[str]] = {n: set() for n in known}
    external: dict[str, set[str]] = {n: set() for n in known}
    unresolved_ambiguous = 0
    for name, v in mods.items():
        for chain in v["chains"]:
            hit = None
            stop = False
            for cand in chain:                      # longest first
                owners = alias_map.get(cand)
                if not owners:
                    continue
                if len(owners) > 1:
                    unresolved_ambiguous += 1
                    stop = True
                    break
                hit = next(iter(owners))
                break
            if stop:
                continue
            if hit is None:
                external[name].add(chain[-1].split(".")[0])
            elif hit != name:
                edges[name].add(hit)

    imported_by: dict[str, set[str]] = {n: set() for n in known}
    for src, dsts in edges.items():
        for d in dsts:
            imported_by[d].add(src)

    is_test = {n: ("tests/" in v["rel"] or v["rel"].startswith("tests/"))
               for n, v in mods.items()}
    covered = {n for n in known
               if any(is_test[s] for s in imported_by[n])}

    # A package `__init__.py` is EXECUTED whenever any submodule of it is imported, so
    # "nothing imports it" is false for a package by construction. Excluded by an exact
    # rule, not by a heuristic, and the exclusion is stated in the rendered prose.
    is_package = {n: v["rel"].endswith("__init__.py") for n, v in mods.items()}
    unreferenced_modules = sorted(
        n for n in known
        if not imported_by[n] and not is_test[n] and not is_package[n])

    # SYMBOLS. A symbol is "referenced elsewhere" when its name appears in ANY other
    # module's name/attribute set. Same-name collisions across modules therefore mask a
    # dead symbol -- a FALSE NEGATIVE, which is the safe direction, and it is disclosed.
    refs_by_other: dict[str, set[str]] = {}
    for name, v in mods.items():
        for r in v["refs"]:
            refs_by_other.setdefault(r, set()).add(name)
    lonely: dict[str, list[str]] = {}
    internal_only: dict[str, list[str]] = {}
    n_symbols = 0
    for name, v in mods.items():
        for s in sorted(v["symbols"]):
            if DUNDER_RE.match(s):
                continue
            n_symbols += 1
            users = refs_by_other.get(s, set())
            if not users:
                lonely.setdefault(name, []).append(s)
            elif users == {name}:
                internal_only.setdefault(name, []).append(s)

    pkg_of = {}
    for n, v in mods.items():
        rel = v["rel"]
        pkg_of[n] = rel.rsplit("/", 1)[0] if "/" in rel else "(repo root)"
    packages: dict[str, list[str]] = {}
    for n, p in pkg_of.items():
        packages.setdefault(p, []).append(n)

    return {
        "edges": edges, "external": external, "imported_by": imported_by,
        "is_test": is_test, "covered": covered, "packages": packages,
        "unreferenced_modules": unreferenced_modules, "lonely": lonely,
        "internal_only": internal_only, "is_package": is_package,
        "n_symbols": n_symbols, "pkg_of": pkg_of,
        "ambiguous": ambiguous, "unresolved_ambiguous": unresolved_ambiguous,
    }


# --------------------------------------------------------------------------- probe

# THE PROBE SOURCES ARE COPIED FROM THE REAL TREE'S SHAPES, not invented.
# The first version of this generator passed 22/22 against sources I made up, then reported
# three internal edges across seventy-nine modules and zero test coverage -- both impossible.
# The fixture had agreed with my resolver because I had written both. Every shape below was
# read out of `ai_engine/` with git grep first (S100), including the sys.path.append that
# creates the second root and the function-level imports that make up most of mad_runner.py.
PROBE_SOURCES = {
    "ai_engine/__init__.py": "",
    "ai_engine/analysis/__init__.py": "",
    "ai_engine/tests/__init__.py": "",
    "ai_engine/mad_runner.py": (
        "import os\n"
        "import sys\n"
        "from dotenv import load_dotenv\n"
        "sys.path.append(os.path.dirname(os.path.abspath(__file__)))\n"
        "from quota_guard import check_quota\n"
        "def run():\n"
        "    from analysis.mad_protocol import run_mad_protocol\n"
        "    return run_mad_protocol(check_quota())\n"
    ),
    "ai_engine/quota_guard.py": "def check_quota():\n    return True\n",
    "ai_engine/groq_guardian.py": "def validate_response(x):\n    return x\n",
    "ai_engine/analysis/mad_protocol.py": (
        "import sys, os\n"
        "sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))\n"
        "def run_mad_protocol(q):\n    return q\n"
        "NEVER_READ_ANYWHERE = 1\n"
        "PRIVATE_SEED = 2\n"
        "def _uses_seed():\n    return PRIVATE_SEED\n"
    ),
    "ai_engine/tests/test_groq_guardian.py": (
        "import sys\n"
        "from groq_guardian import validate_response\n"
        "def test_it():\n    assert validate_response(1) == 1\n"
    ),
    "ai_engine/analysis/orphan_module.py": "import os\nORPHAN_ONLY = 3\n",
    "tools/gni_macro_map.py": "def parse_rules(p):\n    return None\n",
    "tools/gni_rule_checks.py": (
        "import gni_macro_map\n"
        "def go():\n    return gni_macro_map.parse_rules('x')\n"
    ),
    # AMBIGUITY: two files answer to the bare name `helper` once each directory is a root.
    "ai_engine/funnel/__init__.py": "",
    "ai_engine/geo/__init__.py": "",
    "ai_engine/funnel/helper.py": "A = 1\n",
    "ai_engine/geo/helper.py": "B = 2\n",
}


def control_probe() -> tuple[list[str], int]:
    """Assert the instrument's expectations against synthetic sources with KNOWN answers,
    before one real file is read. The count is COUNTED, never written down: C5 / R-S81-5
    forbids a check holding a hand-written expected integer, and `gni_state.py` line 323
    still prints a literal that is only accidentally correct."""
    import tempfile

    fails: list[str] = []
    n = 0

    # --- module naming, including the case this repo actually has both of -------------
    with tempfile.TemporaryDirectory() as td:
        root = Path(td)
        for rel, body in PROBE_SOURCES.items():
            p = root / rel
            p.parent.mkdir(parents=True, exist_ok=True)
            p.write_text(body, encoding="utf-8")
        cases = [
            ("ai_engine/mad_runner.py", "ai_engine.mad_runner", "canonical, repo-root name"),
            ("tools/gni_macro_map.py", "gni_macro_map",
             "NEGATIVE: tools/ has no __init__.py, so no package prefix"),
            ("ai_engine/__init__.py", "ai_engine", "the package itself"),
        ]
        for rel, want, label in cases:
            n += 1
            got = module_name(root / rel, root)
            if got != want:
                fails.append("%s: %s -> %r, expected %r" % (label, rel, got, want))

        # --- one file, several names, because the tree appends its own roots -------------
        n += 1
        al = aliases_of(root / "ai_engine/analysis/mad_protocol.py",
                        [root, root / "ai_engine", root / "ai_engine/analysis"])
        if not {"ai_engine.analysis.mad_protocol", "analysis.mad_protocol",
                "mad_protocol"} <= al:
            fails.append("aliases_of missed a real name for mad_protocol: %r" % (sorted(al),))

        # --- BOM: the trap gni_rule_checks.py documented at its line 66 ---------------
        n += 1
        try:
            ast.parse(decode(b"\xef\xbb\xbfx = 1\n"))
        except SyntaxError:
            fails.append("decode() does not strip the BOM; ast.parse dies on six real files")
        n += 1
        try:
            ast.parse("\ufeffx = 1\n")
            fails.append("the probe itself is wrong: a raw BOM was supposed to break ast.parse")
        except SyntaxError:
            pass

        # --- the whole graph, end to end, against known answers -----------------------
        sh(["git", "init", "-q"], cwd=root)
        sh(["git", "add", "-A"], cwd=root)
        sh(["git", "-c", "user.email=p@p", "-c", "user.name=p", "commit", "-qm", "p"], cwd=root)
        try:
            snap = collect(root)
            a = analyse(snap)
        except ValueError as exc:
            return fails + ["collect/analyse refused the probe tree: %s" % exc], n + 1

        mr = a["edges"].get("ai_engine.mad_runner", set())
        n += 1
        if "ai_engine.quota_guard" not in mr:
            fails.append("`from quota_guard import ...` (sibling, via the appended root) "
                         "must resolve; got %r" % (sorted(mr),))
        n += 1
        if "ai_engine.analysis.mad_protocol" not in mr:
            fails.append("a FUNCTION-LEVEL `from analysis.mad_protocol import ...` must "
                         "resolve; got %r" % (sorted(mr),))
        n += 1
        if a["edges"].get("ai_engine.tests.test_groq_guardian") != {"ai_engine.groq_guardian"}:
            fails.append("a test importing a sibling by bare name must resolve; got %r"
                         % (a["edges"].get("ai_engine.tests.test_groq_guardian"),))
        n += 1
        if not a["covered"] & {"ai_engine.groq_guardian"}:
            fails.append("test coverage must be non-empty when a test imports a module")
        n += 1
        if a["edges"].get("gni_rule_checks") != {"gni_macro_map"}:
            fails.append("bare-name import inside tools/ must resolve; got %r"
                         % (a["edges"].get("gni_rule_checks"),))

        ext = a["external"].get("ai_engine.mad_runner", set())
        n += 1
        if not {"os", "sys", "dotenv"} <= ext:
            fails.append("stdlib/third-party must land in `external`, got %r" % (sorted(ext),))
        n += 1
        if {"os", "sys", "dotenv"} & mr:
            fails.append("NEGATIVE: an external import must NOT become an internal edge")

        # --- ambiguity is COUNTED, never guessed -----------------------------------------
        n += 1
        if "helper" not in a["ambiguous"]:
            fails.append("two files answering to `helper` must be recorded as ambiguous")
        n += 1
        if len(a["ambiguous"].get("helper", [])) != 2:
            fails.append("the ambiguous alias must name BOTH owners")

        # --- path-root sites ---------------------------------------------------------------
        n += 1
        if snap["modules"]["ai_engine.mad_runner"]["path_sites"] != 1:
            fails.append("sys.path.append must be counted where it exists")
        n += 1
        if snap["modules"]["ai_engine.quota_guard"]["path_sites"] != 0:
            fails.append("NEGATIVE: a module with no sys.path call must count zero")

        # --- orphan + symbols --------------------------------------------------------------
        n += 1
        if "ai_engine.analysis.orphan_module" not in a["unreferenced_modules"]:
            fails.append("a module nothing imports must be listed, got %r"
                         % (a["unreferenced_modules"],))
        n += 1
        if "ai_engine.quota_guard" in a["unreferenced_modules"]:
            fails.append("NEGATIVE: quota_guard IS imported and must not be listed")
        n += 1
        if "ai_engine" in a["unreferenced_modules"]:
            fails.append("NEGATIVE: a package __init__ is executed by any submodule import")

        lon = a["lonely"].get("ai_engine.analysis.mad_protocol", [])
        n += 1
        if "NEVER_READ_ANYWHERE" not in lon:
            fails.append("a symbol read nowhere must be listed, got %r" % (lon,))
        n += 1
        if "PRIVATE_SEED" in lon:
            fails.append("NEGATIVE: PRIVATE_SEED is read inside its own module")
        n += 1
        if "run_mad_protocol" in lon:
            fails.append("NEGATIVE: run_mad_protocol is read by mad_runner")

    # --- resolution, isolated ----------------------------------------------------------
    known = {"a.b", "a.b.c"}
    n += 1
    if resolve("a.b.c.d", known) != "a.b.c":
        fails.append("resolve() must take the LONGEST matching prefix")
    n += 1
    if resolve("zzz", known) is not None:
        fails.append("NEGATIVE: an unknown target must resolve to None, not to a guess")

    # --- relative imports must REFUSE, not resolve wrongly ------------------------------
    n += 1
    tgts, rel_forms = imports_of(ast.parse("from . import x\n"))
    if not rel_forms:
        fails.append("a relative import must be reported so analyse() can refuse")

    # --- hashing -----------------------------------------------------------------------
    n += 1
    if norm_md5(b"a\r\nb\r\n") != norm_md5(b"a\nb\n"):
        fails.append("norm_md5 is not EOL-invariant (R-S98-3)")
    n += 1
    if norm_md5(b"\xef\xbb\xbfa\n") != norm_md5(b"a\n"):
        fails.append("norm_md5 does not strip the BOM (R-S98-3)")
    n += 1
    if norm_md5(b"a\n") == norm_md5(b"b\n"):
        fails.append("NEGATIVE: norm_md5 must distinguish different content")
    return fails, n


# --------------------------------------------------------------------------- render

def render(snap: dict, a: dict) -> str:
    mods = snap["modules"]
    o: list[str] = []
    o.append("## §5 BUILDING BLOCK VIEW — **GENERATED**")
    o.append("")
    o.append("**GENERATED by `tools/gni_blocks.py` from the AST of %d tracked `*.py` at HEAD "
             "`%s` — source manifest md5 `%s` (EOL-normalised, R-S98-3). This section carries "
             "NO clock of its own: re-running it on an unchanged tree reproduces these bytes "
             "exactly. Do not hand-edit — the next run overwrites it. If this section is "
             "absent, the generator failed and that absence is the signal.**"
             % (len(mods), snap["head"], snap["manifest_md5"]))
    o.append("")
    o.append("**Section 5 is what is WRITTEN. Section 6 is what ACTUALLY RAN; section 7 is what "
             "is DECLARED. Whether a workflow invokes a module directly is §7.1's entrypoint "
             "column, not this section's — see 5.6.**")
    o.append("")

    # 5.1 ------------------------------------------------------------------
    o.append("### 5.0 The path roots this tree creates for itself")
    o.append("")
    sites = sorted(((v["path_sites"], n) for n, v in mods.items() if v["path_sites"]),
                   reverse=True)
    o.append("**%d modules call `sys.path.append` or `sys.path.insert`, %d calls in total.** "
             "This is not a footnote: it is why a single file answers to several names. "
             "`ai_engine/mad_runner.py` puts its own directory on the path, so its siblings "
             "import each other as `from quota_guard import ...` and its subpackages as "
             "`from analysis.mad_protocol import ...` — never by the `ai_engine.` prefix a "
             "package-relative reader would expect. Every name below is resolved against "
             "every root the tree creates, and a name claimed by two files produces NO edge."
             % (len(sites), sum(k for k, _ in sites)))
    o.append("")
    if sites:
        o.append("| module | `sys.path` calls |")
        o.append("|---|---|")
        for k, n_ in sites:
            o.append("| `%s` | %d |" % (n_, k))
        o.append("")
    amb = a["ambiguous"]
    o.append("**Ambiguous names: %d.** %s"
             % (len(amb),
                "An import naming one of these could mean either file, so this generator "
                "records it and creates no edge — %d import statements were dropped that way."
                % a["unresolved_ambiguous"] if amb else "No name is claimed by two files."))
    if amb:
        o.append("")
        o.append("| name | claimed by |")
        o.append("|---|---|")
        for al in sorted(amb):
            o.append("| `%s` | %s |" % (al, ", ".join("`%s`" % x for x in amb[al])))
    o.append("")
    o.append("### 5.1 Module inventory by package")
    o.append("")
    o.append("| package | modules | internal imports out | imported by |")
    o.append("|---|---|---|---|")
    for pkg in sorted(a["packages"]):
        names = a["packages"][pkg]
        out_e = sum(len(a["edges"][n]) for n in names)
        in_e = sum(len(a["imported_by"][n]) for n in names)
        o.append("| `%s` | %d | %d | %d |" % (pkg, len(names), out_e, in_e))
    o.append("")

    # 5.2 ------------------------------------------------------------------
    o.append("### 5.2 What each module imports, and who imports it")
    o.append("")
    o.append("Internal edges only. An import that resolves to no module in the tree is "
             "EXTERNAL and counted in the last column; this generator deliberately does not "
             "split stdlib from third-party, because doing so needs a hand-written list and a "
             "hand-written list is what C5 forbids.")
    o.append("")
    o.append("| module | file | imports (internal) | imported by | external |")
    o.append("|---|---|---|---|---|")
    for name in sorted(mods):
        e = sorted(a["edges"][name])
        ib = sorted(a["imported_by"][name])
        o.append("| `%s` | `%s` | %s | %s | %d |"
                 % (name, mods[name]["rel"],
                    ", ".join("`%s`" % x for x in e) or "—",
                    ", ".join("`%s`" % x for x in ib) or "**none**",
                    len(a["external"][name])))
    o.append("")

    # 5.3 ------------------------------------------------------------------
    o.append("### 5.3 Modules with NO STATIC REFERENCE FOUND")
    o.append("")
    o.append("Nothing in the tree imports these, and they are not test modules. **This is not "
             "a deletion list.** A module can be reached by a workflow entrypoint, by "
             "`python -m`, or by a name built at run time — none of which an AST sees. Read "
             "this beside §7.1's entrypoint column before concluding anything.")
    o.append("")
    if not a["unreferenced_modules"]:
        o.append("**None** — every non-test module is imported by at least one other.")
    else:
        o.append("| module | file | in §7.1's entrypoint column? |")
        o.append("|---|---|---|")
        for n in a["unreferenced_modules"]:
            o.append("| `%s` | `%s` | *check §7.1* |" % (n, mods[n]["rel"]))
    o.append("")

    # 5.4 ------------------------------------------------------------------
    o.append("### 5.4 Module-level symbols with NO STATIC REFERENCE FOUND ANYWHERE")
    o.append("")
    n_lonely = sum(len(v) for v in a["lonely"].values())
    n_internal = sum(len(v) for v in a["internal_only"].values())
    o.append("**%d of %d** module-level symbols (dunders excluded). A symbol here is defined "
             "at module level and its name is READ nowhere in the tree — not by another "
             "module and not by its own. This is the class that produced DET-DEAD and "
             "`_FORCE_PROVIDER`, five months apart, both found by accident."
             % (n_lonely, a["n_symbols"]))
    o.append("")
    o.append("A further **%d** are read only inside the module that defines them. Those are "
             "private helpers, not candidates, and are not listed. An earlier draft of this "
             "generator counted them here and the table came out at 27 of 31 rows — a true "
             "statement with no signal in it." % n_internal)
    o.append("")
    if not a["lonely"]:
        o.append("**None.**")
    else:
        o.append("| module | symbols |")
        o.append("|---|---|")
        for name in sorted(a["lonely"]):
            syms = a["lonely"][name]
            o.append("| `%s` | %s |" % (name, ", ".join("`%s`" % s for s in syms)))
    o.append("")

    # 5.5 ------------------------------------------------------------------
    o.append("### 5.5 Which modules a test module imports")
    o.append("")
    tests = sorted(n for n in mods if a["is_test"][n])
    non_test = [n for n in mods if not a["is_test"][n]]
    o.append("**%d test modules import %d of the %d non-test modules.** Coverage here means "
             "ONE THING ONLY: a test module names it in an import. It does not mean the "
             "module's behaviour is asserted, and it does not mean the test passes — "
             "36 assertions in `ai_engine/tests/` have never been run in CI (order item)."
             % (len(tests), len(a["covered"] & set(non_test)), len(non_test)))
    o.append("")
    o.append("| test module | imports |")
    o.append("|---|---|")
    for t in tests:
        e = sorted(a["edges"][t])
        o.append("| `%s` | %s |" % (t, ", ".join("`%s`" % x for x in e) or "—"))
    o.append("")
    uncovered = sorted(n for n in non_test if n not in a["covered"])
    o.append("**Imported by no test module (%d):** %s"
             % (len(uncovered), ", ".join("`%s`" % n for n in uncovered) or "none"))
    o.append("")

    # 5.6 ------------------------------------------------------------------
    o.append("### 5.6 What §5 does not answer")
    o.append("")
    o.append("- **Whether an import is CALLED.** This is a static reader. `imports X` is not "
             "`calls X at run time`; §6 holds the runtime side.")
    o.append("- **Dynamic reference.** `getattr`, a name assembled from a string, a plugin "
             "registry, an `__all__` re-export and a CLI entrypoint are all invisible here. "
             "Every column above therefore says NO STATIC REFERENCE FOUND and never `dead`.")
    o.append("- **Same-name collisions mask a lonely symbol.** 5.4 matches symbol names across "
             "the whole tree, so a symbol called `main` is never reported even when this "
             "module's `main` is unused. The failure direction is a FALSE NEGATIVE — the "
             "section under-reports rather than accusing live code — and that is deliberate.")
    o.append("- **Whether a workflow runs a module.** §7.1's entrypoint column. Joining the "
             "two tables is the reader's job and both halves stay true; this generator does "
             "not parse YAML.")
    o.append("- **pytest discovery.** `test_*` functions and `Test*` classes are found by "
             "NAME at run time, so 5.4 lists them as unreferenced. They are collected by the "
             "runner, not called by any module. Read that block with this in mind.")
    o.append("- **Untracked files.** The inventory is `git ls-files '*.py'`. A file that is "
             "not tracked is not architecture.")
    o.append("")
    return "\n".join(o)


def splice(src_text: str, section: str) -> str:
    lines = src_text.splitlines()
    start = end = None
    for i, ln in enumerate(lines):
        if start is None and ln.startswith("## §5"):
            start = i
        elif start is not None and ln.startswith("## §6"):
            end = i
            break
    if start is None or end is None:
        raise ValueError("could not locate the §5..§6 boundary in the source document")
    return "\n".join(lines[:start] + section.splitlines() + lines[end:]) + "\n"


# --------------------------------------------------------------------------- main

def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(add_help=True)
    ap.add_argument("--session", type=int, required=True,
                    help="session number; names the OUTPUT document. No default on purpose: "
                         "gni_state.py's default=94 writes S98 content under an S94 name "
                         "(item 5.34).")
    ap.add_argument("--src", default=None)
    ap.add_argument("--stdout", action="store_true")
    args = ap.parse_args(argv)

    fails, n_probe = control_probe()
    if fails:
        print("CONTROL PROBE FAILED -- nothing written. The instrument is wrong, "
              "not the repo:", file=sys.stderr)
        for f in fails:
            print("  - " + f, file=sys.stderr)
        return 2
    print("CONTROL PROBE: %d/%d pass (naming, aliases across path roots, BOM, sibling + "
          "function-level + bare-name edges, external negatives, ambiguity, sys.path sites, "
          "orphan module, package exclusion, lonely vs private symbols, EOL hashing)"
          % (n_probe, n_probe))

    try:
        snap = collect(ROOT)
        a = analyse(snap)
    except ValueError as exc:
        print("REFUSING: %s" % exc, file=sys.stderr)
        return 2
    section = render(snap, a)

    if args.stdout:
        print(section)
        return 0

    if args.src:
        src = Path(args.src)
    else:
        cands = sorted(DOCS.glob("GNI_ARCHITECTURE_S*.md"),
                       key=lambda p: int(re.sub(r"\D", "", p.stem) or 0))
        if not cands:
            print("MISSING: no GNI_ARCHITECTURE_S*.md under %s" % DOCS, file=sys.stderr)
            return 3
        src = cands[-1]
    if not src.is_file():
        print("MISSING: %s" % src, file=sys.stderr)
        return 3
    out = DOCS / ("GNI_ARCHITECTURE_S%d.md" % args.session)
    try:
        text = splice(src.read_text(encoding="utf-8"), section)
    except ValueError as exc:
        print("REFUSING: %s (source: %s)" % (exc, src), file=sys.stderr)
        return 2
    out.write_text(text, encoding="utf-8", newline="\n")
    print("SOURCE : %s" % src.name)
    print("WROTE  : %s  (%d bytes)" % (out.relative_to(ROOT), len(text)))
    print("§5 covers %d modules, %d internal edges, %d with no static reference, "
          "%d lonely symbols of %d"
          % (len(snap["modules"]), sum(len(v) for v in a["edges"].values()),
             len(a["unreferenced_modules"]),
             sum(len(v) for v in a["lonely"].values()), a["n_symbols"]))
    return 0


if __name__ == "__main__":
    sys.exit(main())
