#!/usr/bin/env python3
"""tools/patch_s104_fixture.py - S104 item 5.54, the fixture half.

C8 is the first check in this repo that needs a git INDEX: gni_blocks.tracked_py
runs `git ls-files '*.py'`. The fixture builds its trees with tempfile.mkdtemp,
which is not a repository, so collect() raises and main() returns 2 for EVERY
family. base() therefore inits a repo and commits once.

The architecture the fixture writes also carries no GENERATED stamp at all, so
arch_stamps would raise on the clean tree. Three stamps are appended, each with
its fingerprint COMPUTED from the tree as built -- never hard-coded -- by the
same generators C8 imports. A fixture stamp is wrong only if the generator is.

Order inside base() is load-bearing and unchanged in spirit: the stamps go in
BEFORE the map is written, because the map hashes the finished architecture.

Binary mode throughout (GNI-L-001); every anchor is pure ASCII (GNI-L-015).
Run from the repo root:   python tools/patch_s104_fixture.py
Refuses and changes nothing if any anchor is missing or not unique.
"""
import sys

PATH = "tools/gni_rule_checks_fixture.py"
EDITS = []


def edit(old, new, label):
    EDITS.append((old.encode("utf-8"), new.encode("utf-8"), label))


# ------------------------------------------------------------------ helpers
edit(
    '''def ap(p, s):''',
    '''def _git_index(root):
    """C8 reads section five's fingerprint through gni_blocks.collect, which
    lists the git INDEX. A tempfile tree is not a repository, so without this
    every family returns 2 on an instrument error and the fixture measures
    nothing. One commit, so HEAD resolves too; identity is passed with -c
    rather than written, so no global git config is touched."""
    import subprocess
    def run(*args):
        subprocess.run(("git",) + args, cwd=root, check=True,
                       stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
    run("init", "-q")
    run("add", "-A")
    run("-c", "user.email=fixture@local", "-c", "user.name=fixture",
        "commit", "-q", "-m", "fixture tree")


def _gen_stamps(root):
    """The three GENERATED-section stamps C8 reads. Every fingerprint is
    computed from the tree AS BUILT, using the generator's own hasher -- the
    discipline _map_text already follows, and the reason the fixture survives
    CRLF on Windows. A hard-coded md5 here would make the families agree with
    the fixture's memory instead of with the tree.

    The HEAD and count fields are deliberately junk: C8 reads neither, and
    writing plausible values would invite a later reader to believe they are
    checked. Section five's HEAD field CANNOT be checked from a working tree
    -- committing the document that carries it advances HEAD -- and that is
    DECISION S104-1, recorded here where it would otherwise be assumed."""
    from pathlib import Path
    import gni_blocks as gb
    import gni_runtime as gr
    import gni_state as gs
    snap = Path(root) / "docs" / "gni_runtime_snapshot_S94.json"
    wfs = sorted((Path(root) / ".github" / "workflows").glob("*.yml"))
    return ("\\n## \\u00a75 BUILDING BLOCK VIEW\\n\\n"
            "**GENERATED by `tools/gni_blocks.py` from the AST of ? tracked `*.py` "
            "at HEAD `unchecked` \\u2014 source manifest md5 `%s` "
            "(EOL-normalised, R-S98-3).**\\n\\n"
            "## \\u00a76 RUNTIME VIEW\\n\\n"
            "**GENERATED by `tools/gni_runtime.py` from "
            "`docs/gni_runtime_snapshot_S94.json` \\u2014 snapshot md5 `%s` "
            "(EOL-normalised, R-S98-3).**\\n\\n"
            "**GENERATED by `tools/gni_state.py` from HEAD `unchecked` \\u2014 "
            "? workflow files, manifest md5 `%s` (EOL-normalised, R-S98-3).**\\n"
            % (gb.collect(Path(root))["manifest_md5"],
               gr.norm_md5(snap.read_bytes()),
               gs.workflow_manifest(wfs)))


def ap(p, s):''',
    "fixture: _git_index and _gen_stamps helpers",
)

# -------------------------------------------------------------- base() args
edit(
    """def base(root, arch=ARCH_OK, rules=RULES, contract=None,
         map_n_delta=0, map_present=True,
         slo_bound="1", slo_from=None, slo_to=None,
         watcher=WATCHER, snap=None):""",
    """def base(root, arch=ARCH_OK, rules=RULES, contract=None,
         map_n_delta=0, map_present=True,
         slo_bound="1", slo_from=None, slo_to=None,
         watcher=WATCHER, snap=None, extra_arch=None):""",
    "fixture: base() gains extra_arch",
)

# ------------------------------------------------------- base() body, order
edit(
    """    # LAST, and the order is load-bearing: the map stamps the architecture's
    # md5, and the SLO block above APPENDS to the architecture. Stamping before
    # that append would leave every family red on a hash the fixture itself had
    # just invalidated -- the check would look alive while measuring nothing.""",
    """    # The index must exist before the stamps: section five's fingerprint is
    # `git ls-files '*.py'` under the hood, and an untracked tree hashes to a
    # value no generator would ever publish.
    _git_index(root)
    ap(root + "/docs/GNI_ARCHITECTURE_S94.md", _gen_stamps(root))
    if extra_arch:
        ap(root + "/docs/GNI_ARCHITECTURE_S94.md", extra_arch)
    # LAST, and the order is load-bearing: the map stamps the architecture's
    # md5, and the SLO and STAMP blocks above APPEND to the architecture.
    # Stamping before those appends would leave every family red on a hash the
    # fixture itself had just invalidated -- the check would look alive while
    # measuring nothing.""",
    "fixture: base() indexes the tree and appends the stamps before the map",
)

# ----------------------------------------------------------------- families
edit(
    """# Expected verdict per family.""",
    '''# S104, item 5.54. One family per failure shape C8 can detect. 24 is the
# DISCRIMINATOR against C2 (R-S90-1): C2 counts workflows and passes, because
# the counts did not move; only the bytes did. 23 is the liveness shape C6
# learned at S103 -- the named file still exists and still hashes correctly.
CASES["22-sec5-stale-manifest"] = lambda r: (
    base(r), ap(r + "/ai_engine/ok.py", "extra = 1\\n"), r)[-1]
CASES["23-sec6-snapshot-renamed"] = lambda r: (
    base(r), shutil.copyfile(r + "/docs/gni_runtime_snapshot_S94.json",
                             r + "/docs/gni_runtime_snapshot_S95.json"), r)[-1]
CASES["24-sec7-workflow-edited"] = lambda r: (
    base(r), ap(r + "/.github/workflows/a.yml",
                "# fixture edit: bytes move, counts do not\\n"), r)[-1]
CASES["25-arch-unknown-generator"] = lambda r: base(
    r, extra_arch="\\n**GENERATED by `tools/gni_future.py` from HEAD `x` "
                  "\\u2014 manifest md5 `%s` (EOL-normalised).**\\n" % ("0" * 32))

# Expected verdict per family.''',
    "fixture: four C8 families",
)

edit(
    """    "21-map-third-input": 1,
}""",
    """    "21-map-third-input": 1,
    "22-sec5-stale-manifest": 1, "23-sec6-snapshot-renamed": 1,
    "24-sec7-workflow-edited": 1, "25-arch-unknown-generator": 2,
}""",
    "fixture: four C8 expectations",
)


def main():
    try:
        with open(PATH, "rb") as fh:
            blob = fh.read()
    except OSError as exc:
        print("REFUSED: cannot read %s (%s)" % (PATH, exc))
        return 2
    for old, new, label in EDITS:
        n = blob.count(old)
        if n != 1:
            print("REFUSED: anchor for %r matches %d times" % (label, n))
            print("         nothing written. Fix the anchor, do not widen the search.")
            return 2
        blob = blob.replace(old, new)
        print("  ok  %s" % label)
    with open(PATH, "wb") as fh:
        fh.write(blob)
    print("WROTE %s  %d bytes" % (PATH, len(blob)))
    print("\nVERIFY:  python tools/gni_rule_checks_fixture.py")
    print("         expect 25 families, 0 mismatches")
    return 0


if __name__ == "__main__":
    sys.exit(main())
