#!/usr/bin/env python3
"""tools/patch_s104_row4.py - S104 item 5.54, the scoreboard half.

Rewrites row four of the completion test in the LIVE architecture, its status
heading, and the paragraph that reads the table. Every figure below was
measured this session; nothing is carried from prose.

The live document is resolved by RELATION (R-S92-2) -- highest session number,
parsed as an integer -- so this runs correctly whether or not the close has
already renamed the file. Lines are located by unique PREFIX and replaced
whole, so a 1,300-character anchor never has to be transcribed by hand.

Binary mode throughout (LR-078). Run from the repo root:
    python tools/patch_s104_row4.py
Refuses and changes nothing unless every anchor matches exactly once.
"""
import os
import re
import sys

ARCH_RE = re.compile(r"^GNI_ARCHITECTURE_S(\d+)\.md$")

ROW4 = (
    "| 4 | **YES** | `rule_checks` exits 0 on a clean tree and goes RED on every one of the four "
    "surfaces this row names. \u00a77 by COUNT (C2, family `5-stale-generator`) and, since S104, by "
    "BYTES as well (C8, family `24-sec7-workflow-edited`, which edits a workflow without moving any "
    "count and which C2 passes -- the two checks do not overlap). The macro map in both of its "
    "failure shapes (C6, families `19`, `20`, `21`). \u00a75 and \u00a76 by C8, built at S104 for item "
    "**5.54**: it finds every `^**GENERATED by `tools/` stamp the document declares, resolves each "
    "to a fingerprint RULE keyed by the generator that wrote it, recomputes that fingerprint from "
    "the live tree using the generator's own code (R-S96-3), and holds no count of sections "
    "anywhere -- C5's self-lint proves the last clause, since a hand-written integer inside a check "
    "is itself a failure. Families `22-sec5-stale-manifest`, `23-sec6-snapshot-renamed` (LIVENESS: "
    "the named file still exists and still hashes to exactly its stamped value) and "
    "`25-arch-unknown-generator` (a fourth generated section must announce itself, not slip past). "
    "25 families, 0 mismatches. CERTIFIED on two REAL commits with ONE instrument: at `8ce57fc` "
    "today's detector reports 8 checked, 0 failed; at `a923ad9` the same detector reports "
    "`gni_blocks.py: live md5 d7f5ba05...; section stamped bc52f9c0...`. The \u00a75 stamp is "
    "BYTE-IDENTICAL in both trees -- md5 `e1c9488b9df1f5d61f0596a227cc602f`, by "
    "`git show <c>:docs/GNI_ARCHITECTURE_S102.md | grep -m1 '^\\*\\*GENERATED by `tools/gni_blocks' "
    "| tr -d '\\r' | md5sum` -- so the verdicts cannot have come from the document. They came from "
    "the tree. The staleness replayed is the one the S102 close actually shipped, wrong by three "
    "from the moment it was published. **KNOWN LIMIT, disclosed and numbered:** \u00a77's fingerprint "
    "covers WORKFLOW BYTES ONLY; \u00a77.2 also renders `gh secret list`, whose source lies outside "
    "the tree and is unreachable from a harness that carries no secrets by design. A secret added "
    "or removed leaves \u00a77 stale with its published fingerprint still green. That is item "
    "**5.58**, and it is NOT a fifth surface: it is an INPUT to a named surface that no fingerprint "
    "covers -- a configuration-IDENTIFICATION gap, not the configuration-AUDIT gap this row tests "
    "(IEEE 828's two distinct functions). DECISION S104-1 ruled it disclosed here rather than "
    "closed here. |"
)

HEADING = "### STATUS OF THE COMPLETION TEST AT THE S104 CLOSE (four of four)"

PARA = (
    "Every row holds. **ROADMAP 2 IS 4 OF 4**, declared at the S104 close from the evidence in the\n"
    "row above, each figure reproducible by the command printed beside it. DECISION S103-1 ruled at\n"
    "the S103 open that row four is read AS WRITTEN -- it names four surfaces, and the S98 table\n"
    "recorded \u00a75 and \u00a76 as ABSENT rather than excluded -- and that reading is what closed it. The\n"
    "row's own published command settles the claim: flip one source figure and expect a non-zero\n"
    "exit. At the S103 close, flipping a \u00a75 figure still exited 0. It no longer does, for any of\n"
    "the four. DECISION S103-2's other side is therefore not reached: roadmap 3 begins at S105 with\n"
    "roadmap 2 ACHIEVED, not DECLARED NOT ACHIEVED.\n"
    "\n"
    "One field in every stamp is deliberately NOT checked, and cannot be. Each names a HEAD, and\n"
    "committing the document that carries the stamp advances HEAD, so the field is one step behind\n"
    "by construction. That is not a defect and it was already ruled, at S102 in `d9ebebb`: the\n"
    "one-commit lag between harvest and commit is what harvest-then-commit means. None of the three\n"
    "fingerprints takes HEAD as an input, so nothing this row tests depends on it. Recorded here\n"
    "rather than assumed, because a limitation nobody wrote down is indistinguishable from an\n"
    "oversight (IEEE 828 Annex D.3)."
)

REPLACEMENTS = [
    ("| 4 | **PARTIAL - THE MAP HALF IS CLOSED, THE SECTION HALF IS NOT** |", ROW4,
     "row four"),
    ("### STATUS OF THE COMPLETION TEST AT THE S103 CLOSE", HEADING,
     "status heading"),
    ("The failing rows are named, which is the point of the test.", PARA,
     "the paragraph that reads the table"),
]

# The second line of that paragraph is removed with it; located separately so
# the replacement above stays a single-line operation.
DROP_NEXT = {"The failing rows are named, which is the point of the test."}


def live_arch(root):
    docs = os.path.join(root, "docs")
    gens = [(int(m.group(1)), n) for n in os.listdir(docs)
            for m in [ARCH_RE.match(n)] if m]
    if not gens:
        raise SystemExit("REFUSED: no architecture document under " + docs)
    return os.path.join(docs, max(gens)[-1])


def main():
    path = live_arch(".")
    print("LIVE (by RELATION): %s" % path)
    with open(path, "rb") as fh:
        blob = fh.read()
    if b"\r\n" in blob:
        print("REFUSED: %s holds CRLF; this patch assumes LF" % path)
        return 2

    lines = blob.split(b"\n")
    for prefix, new, label in REPLACEMENTS:
        pb = prefix.encode("utf-8")
        hits = [i for i, ln in enumerate(lines) if ln.startswith(pb)]
        if len(hits) != 1:
            print("REFUSED: prefix for %r matches %d lines" % (label, len(hits)))
            print("         nothing written.")
            return 2
        i = hits[0]
        if prefix in DROP_NEXT:
            del lines[i + 1]
        lines[i] = new.encode("utf-8")
        print("  ok  %s  (line %d)" % (label, i + 1))

    out = b"\n".join(lines)
    with open(path, "wb") as fh:
        fh.write(out)
    print("WROTE %s  %d bytes" % (path, len(out)))
    print("\nVERIFY:")
    print("  grep -n 'ROADMAP 2 IS 4 OF 4' %s" % path)
    print("  python tools/gni_rule_checks.py .      # C1 must still pass: 5.58 is not an id")
    return 0


if __name__ == "__main__":
    sys.exit(main())
