#!/usr/bin/env python3
"""tools/patch_s104_c8.py - S104 item 5.54.

The executable record of how these bytes changed. Two files, five edits, all
anchored on text that exists exactly once. Binary mode throughout (LR-078);
every anchor is pure ASCII (LR-101).

  gni_state.py         workflow_manifest() lifted out of main(), IMPORTABLE
  gni_rule_checks.py   live_snapshot_path, arch_stamps, three fingerprint
                       rules, check_c8, one control probe, one CHECKS row

Run from the repo root:   python tools/patch_s104_c8.py
Refuses and changes nothing if any anchor is missing or not unique.
"""
import sys

EDITS = []


def edit(path, old, new, label):
    EDITS.append((path, old.encode("utf-8"), new.encode("utf-8"), label))


# ---------------------------------------------------------------- gni_state
# The §7 fingerprint was computed inline inside main(), so nothing outside
# main() could recompute it. C6's docstring settles why a copy in the detector
# is not an option: "A second parser here would be a second opinion, not a
# check (R-S96-3)." The expression is moved, not rewritten -- the bytes it
# produces are identical and `cmp` proves it.
edit(
    "tools/gni_state.py",
    """def render(wfs: list[dict], stored: list[str], stored_note: str, head: str,
           manifest: str) -> str:""",
    '''def workflow_manifest(wf_paths: list[Path]) -> str:
    """The §7 fingerprint: one EOL-normalised md5 over `name<TAB>md5` per
    workflow file, in the order given. MODULE-LEVEL ON PURPOSE, exactly as
    gni_blocks.collect and gni_runtime.norm_md5 are, so that C8 recomputes this
    section's declared value with THIS code rather than with a second opinion
    (R-S96-3). Lifted out of main() unchanged at S104; the expression is moved,
    not rewritten."""
    return norm_md5("\\n".join(
        f"{p.name}\\t{norm_md5(p.read_bytes())}" for p in wf_paths).encode("utf-8"))


def render(wfs: list[dict], stored: list[str], stored_note: str, head: str,
           manifest: str) -> str:''',
    "gni_state: workflow_manifest() lifted out of main()",
)

edit(
    "tools/gni_state.py",
    """    manifest = norm_md5("\\n".join(
        f"{p.name}\\t{norm_md5(p.read_bytes())}" for p in wf_paths).encode("utf-8"))""",
    """    manifest = workflow_manifest(wf_paths)""",
    "gni_state: main() calls the lifted helper",
)

# ------------------------------------------------------------ rule_checks 1
# C8 lands after C6 and before C7's helpers. Anchored on C6's own final return,
# which appears once.
C8_SOURCE = '''

SNAP_RE = re.compile(r"^gni_runtime_snapshot_S(\\d+)\\.json$")
ARCH_STAMP_RE = re.compile(
    r"^\\*\\*GENERATED by `tools/(?P<tool>[A-Za-z0-9_]+\\.py)`(?P<rest>[^\\n]*)", re.M)
MD5_IN_STAMP = re.compile(r"md5 `([0-9a-f]+)`")
FROM_IN_STAMP = re.compile(r"from `([^`]+)`")


def live_snapshot_path(root):
    """The highest-numbered runtime snapshot. Same RELATION rule as live_docs
    and live_map_path: parsed as an integer, never a lexical sort and never a
    list position (R-S92-2)."""
    docs = os.path.join(root, "docs")
    if not os.path.isdir(docs):
        raise InstrumentError("missing dir: " + docs)
    gens = [(int(m.group(1)), n) for n in os.listdir(docs)
            for m in [SNAP_RE.match(n)] if m]
    require_nonempty("runtime snapshot generations", gens)
    return os.path.join(docs, max(gens)[-1])


def arch_stamps(body):
    """Every generated-section stamp the ARCHITECTURE declares, in the order
    written. Anchored at LINE START and on the literal `tools/` because the
    completion test's own prose contains the words GENERATED by and publishes
    md5s of its own: measured at S104, a loose pattern matches four stamps
    where three exist, and the fourth is the scoreboard that grades this check.
    A check must not derive its target from what the target names (R-S103-1).

    Zero is an INSTRUMENT ERROR and never an empty list: a renamed stamp format
    must halt, not report an architecture with nothing left to check
    (R-S81-1)."""
    rows = [(m.group("tool"), m.group("rest"))
            for m in ARCH_STAMP_RE.finditer(body)]
    return require_nonempty("architecture GENERATED stamps", rows)


def _blocks_fingerprint(ctx, rest):
    """§5. The generator's own collector, over the LIVE tree."""
    from pathlib import Path
    import gni_blocks as gb
    try:
        snap = gb.collect(Path(ctx["root"]))
    except ValueError as exc:
        raise InstrumentError("the generator's own collector refused: %s" % exc)
    return snap["manifest_md5"], None


def _runtime_fingerprint(ctx, rest):
    """§6. Two ways to be stale, and the second is the one S102 actually
    suffered on the macro map: the named snapshot still exists and still hashes
    to exactly its stamped value while no longer being the live one. Liveness
    is reported with no md5 in the message at all."""
    from pathlib import Path
    import gni_runtime as gr
    named = FROM_IN_STAMP.search(rest)
    if not named:
        raise InstrumentError("the gni_runtime stamp names no snapshot")
    live = live_snapshot_path(ctx["root"])
    if os.path.basename(named.group(1)) != os.path.basename(live):
        return None, "reads %s; the live snapshot is %s" % (
            os.path.basename(named.group(1)), os.path.basename(live))
    return gr.norm_md5(Path(live).read_bytes()), None


def _state_fingerprint(ctx, rest):
    """§7. KNOWN LIMIT, disclosed rather than hidden: this fingerprint covers
    WORKFLOW BYTES ONLY. Section 7.2 also renders `gh secret list`, whose
    source is outside the tree and unreachable from CI by this harness's own
    hard boundary -- a secret added or removed leaves the section stale with
    this value still green. DECISION S104-1 ruled that hole DISCLOSED and not
    closed here; it is item 5.58, and its home is the generator's stamp, not
    this check."""
    from pathlib import Path
    import gni_state as gs
    wf_dir = os.path.join(ctx["root"], ".github", "workflows")
    if not os.path.isdir(wf_dir):
        raise InstrumentError("missing dir: " + wf_dir)
    paths = sorted(Path(wf_dir).glob("*.yml"))
    require_nonempty("workflow files", paths)
    return gs.workflow_manifest(paths), None


ARCH_GENERATORS = {
    "gni_blocks.py": _blocks_fingerprint,
    "gni_runtime.py": _runtime_fingerprint,
    "gni_state.py": _state_fingerprint,
}


def check_c8_generated_sections_fresh(ctx):
    """Item 5.54 (C8), the other half of roadmap 2's row four. Every generated
    section of the ARCHITECTURE publishes the fingerprint of what it read.
    Until S104 nothing read any of them: C2 checked section seven's COUNTS
    against the YAML, C6 checked the macro map's declared inputs, and sections
    five and six had no check of any kind.

    That was never hypothetical. Measured at S104 across twenty-four commits:
    section five's declared value disagreed with the live tree at ELEVEN of
    them. It shipped wrong by six at `9e11f57`, correct at `8ce57fc`, wrong by
    three by the S102 close at `a923ad9` -- the same stamp, byte-identical, on
    two trees -- and wrong by one at `60af1a5`, the commit whose own purpose
    was to restamp it.

    HOW IT WORKS. Each stamp is resolved to a fingerprint RULE by the name of
    the generator that wrote it, and the rule recomputes the value from the
    live tree using the generator's own code. No count of sections is written
    anywhere in this file, and a stamp naming a generator with no rule is an
    INSTRUMENT ERROR rather than a silent skip: a fourth generated section must
    announce itself, not slip past.

    NOT CHECKED, and it cannot be: each stamp also names a HEAD. Committing the
    document that carries the stamp advances HEAD, so the field is one step
    behind by construction and no working-tree check can settle it. The
    fingerprints are unaffected -- none of the three takes HEAD as an input --
    so this check reads them and leaves the HEAD field alone. DECISION S104-1
    (IEEE 828 Annex D.3: limitations are recorded, not silently assumed)."""
    docs = require_nonempty("live docs", ctx["docs"])
    arch_path = docs["GNI_ARCHITECTURE"]
    body = require_nonempty("architecture text", read(arch_path))
    stamps = arch_stamps(body)
    problems = []
    for tool, rest in stamps:
        rule = ARCH_GENERATORS.get(tool)
        if rule is None:
            raise InstrumentError("no fingerprint rule for generator: " + tool)
        stamped = MD5_IN_STAMP.search(rest)
        if not stamped:
            raise InstrumentError("the %s stamp declares no md5" % tool)
        live_h, note = rule(ctx, rest)
        if note:
            problems.append("%s: %s" % (tool, note))
        elif stamped.group(1) != live_h:
            problems.append("%s: live md5 %s; section stamped %s"
                            % (tool, live_h, stamped.group(1)))
    if problems:
        return False, "; ".join(problems)
    return True, "%s: %d generated sections resolve live and match" % (
        os.path.basename(arch_path), len(stamps))
'''

edit(
    "tools/gni_rule_checks.py",
    '''    return True, "%s: %d INPUT lines resolve live and match, %d markers" % (
        os.path.basename(map_path), len(inputs), live_n)
''',
    '''    return True, "%s: %d INPUT lines resolve live and match, %d markers" % (
        os.path.basename(map_path), len(inputs), live_n)
''' + C8_SOURCE,
    "rule_checks: C8 and its helpers inserted after C6",
)

# ------------------------------------------------------------ rule_checks 2
edit(
    "tools/gni_rule_checks.py",
    """    ("C7 SLO-2+3  freshness bound", check_c7_slo_freshness),
)""",
    """    ("C7 SLO-2+3  freshness bound", check_c7_slo_freshness),
    ("C8 R-S104-1 generated sections", check_c8_generated_sections_fresh),
)""",
    "rule_checks: C8 registered",
)

# ------------------------------------------------------------ rule_checks 3
edit(
    "tools/gni_rule_checks.py",
    """    body = read(live_map_path(root))
    _probe_halts("a renamed INPUT line still parsed", map_inputs,
                 body.replace("INPUT `", "XX-RENAMED-XX `"))""",
    """    body = read(live_map_path(root))
    _probe_halts("a renamed INPUT line still parsed", map_inputs,
                 body.replace("INPUT `", "XX-RENAMED-XX `"))
    arch = read(live_docs(root)["GNI_ARCHITECTURE"])
    _probe_halts("a renamed GENERATED stamp still parsed", arch_stamps,
                 arch.replace("**GENERATED by `tools/", "XX-RENAMED-XX `tools/"))""",
    "rule_checks: control probe for the stamp format",
)


def main():
    loaded = {}
    for path, old, new, label in EDITS:
        if path not in loaded:
            try:
                with open(path, "rb") as fh:
                    loaded[path] = fh.read()
            except OSError as exc:
                print("REFUSED: cannot read %s (%s)" % (path, exc))
                return 2
        n = loaded[path].count(old)
        if n != 1:
            print("REFUSED: anchor for %r matches %d times in %s" % (label, n, path))
            print("         nothing written. Fix the anchor, do not widen the search.")
            return 2
        loaded[path] = loaded[path].replace(old, new)
        print("  ok  %s" % label)

    for path, blob in loaded.items():
        with open(path, "wb") as fh:
            fh.write(blob)
        print("WROTE %s  %d bytes" % (path, len(blob)))
    print("\nVERIFY, in this order:")
    print("  python tools/gni_state.py --no-gh --stdout > /dev/null && echo state-ok")
    print("  python tools/gni_rule_checks.py .")
    return 0


if __name__ == "__main__":
    sys.exit(main())
