#!/usr/bin/env python3
"""tools/patch_s104_spec.py - S104, the roadmap 3 specification.

WHY THIS IS NOT THE PATCH S102 WROTE. That draft hard-coded
`docs/GNI_ROADMAP3_SPEC_S102.md`. A generation _S103 exists and is the LIVE
file of the family, so the draft would have edited a SUPERSEDED document -
rewriting frozen history - and left the live one untouched. It is the exact
failure C6 was rewritten for at S103 and C8 was built for at S104: resolving a
file by the name something states rather than by RELATION. The live file is
resolved here, never named.

The draft also guarded on a raw md5 of a checked-out file and told the reader
to STOP if it differed. On Windows that number is platform noise, not evidence
(R-S98-3, and the NINTH CARRY). The guard here is the anchor count instead:
zero or several matches and nothing is written.

The live file needs no correction - S103 already corrected S102's prediction,
in its AMENDMENT NOTICE and in the S103 row itself. What it needs is the S104
row's own forward claim RESOLVED, because that row still says "four of four
WITH evidence, or NOT ACHIEVED with the reason" about work that is now done.
Corrected rather than deleted, which is this file's own stated doctrine.

Binary mode (GNI-L-001); every anchor is pure ASCII (GNI-L-015).
Run from the repo root:   python tools/patch_s104_spec.py
"""
import os
import re
import sys

SPEC_RE = re.compile(r"^GNI_ROADMAP3_SPEC_S(\d+)\.md$")

S104_ROW = (
    "| **S104** | DONE. Order item **5.54** shipped (`693ac2b`, `bc88bd8`): `C8` resolves every "
    "`**GENERATED by `tools/` stamp the architecture declares to a fingerprint rule keyed by the "
    "generator that wrote it, and recomputes that fingerprint from the live tree with the "
    "generator's own code. **ROADMAP 2 IS FOUR OF FOUR, DECLARED ACHIEVED** - row four's own "
    "published command now returns non-zero on all four surfaces. Certified on two REAL commits "
    "with one instrument: `8ce57fc` exits 0, `a923ad9` exits 1, on a byte-identical \u00a75 stamp. "
    "25 fixture families, 0 mismatches. CI green at JOB level (`34423999423`: `harnesses` and "
    "`rule_checks` both `success`), which is where the claim is settled - a local green is not a "
    "CI green. This row previously stated the outcome as a choice between two; it is written here "
    "as what happened. |"
)

NOTICE = (
    "**AMENDMENT NOTICE (S104).** The row for S104 below stated an outcome as a choice - four of "
    "four\nWITH evidence, or NOT ACHIEVED with the reason. It resolved: item 5.54 shipped and "
    "roadmap 2 is\nFOUR OF FOUR, declared at the S104 close with the evidence in the row and in "
    "row four of the\ncompletion test itself. Recorded here for the same reason S103 recorded its "
    "correction: this file\nis what S105 opens to, and a plan that never records which branch it "
    "took cannot be audited. The\nremaining open question in this file is unchanged - roadmap 3 "
    "is a PROPOSAL, and committing to it\nis James's declaration, not a prior session's."
)

REPLACEMENTS = [
    ("| **S104** | order item ", S104_ROW, "the S104 sequencing row"),
]
INSERT_AFTER = [
    ("S104 opens to.", NOTICE, "the S104 amendment notice"),
]


def live_spec(root):
    """RELATION (R-S92-2): highest generation, parsed as an integer. The name is
    never assumed - that assumption is what this patch exists to avoid."""
    docs = os.path.join(root, "docs")
    gens = [(int(m.group(1)), n) for n in os.listdir(docs)
            for m in [SPEC_RE.match(n)] if m]
    if not gens:
        raise SystemExit("REFUSED: no roadmap 3 specification under " + docs)
    for g, n in sorted(gens):
        print("  found generation S%d: %s" % (g, n))
    return os.path.join(docs, max(gens)[-1])


def main():
    path = live_spec(".")
    print("LIVE (by RELATION): %s" % path)
    with open(path, "rb") as fh:
        blob = fh.read()
    lines = blob.split(b"\n")

    for prefix, new, label in REPLACEMENTS:
        pb = prefix.encode("utf-8")
        hits = [i for i, ln in enumerate(lines) if ln.startswith(pb)]
        if len(hits) != 1:
            print("REFUSED: prefix for %r matches %d lines; nothing written"
                  % (label, len(hits)))
            return 2
        lines[hits[0]] = new.encode("utf-8")
        print("  ok  replaced %s  (line %d)" % (label, hits[0] + 1))

    for suffix, new, label in INSERT_AFTER:
        sb = suffix.encode("utf-8")
        hits = [i for i, ln in enumerate(lines) if ln.rstrip().endswith(sb)]
        if len(hits) != 1:
            print("REFUSED: suffix for %r matches %d lines; nothing written"
                  % (label, len(hits)))
            return 2
        lines[hits[0] + 1:hits[0] + 1] = [b"", new.encode("utf-8")]
        print("  ok  inserted %s  (after line %d)" % (label, hits[0] + 1))

    out = b"\n".join(lines)
    if (b"\r\n" in out) != (b"\r\n" in blob):
        print("REFUSED: this patch changed the file's line endings")
        return 2
    with open(path, "wb") as fh:
        fh.write(out)
    print("WROTE %s  %d bytes" % (path, len(out)))
    print("\nVERIFY (run twice - the second run must REFUSE):")
    print("  grep -n 'ROADMAP 2 IS FOUR OF FOUR' %s" % path)
    return 0


if __name__ == "__main__":
    sys.exit(main())
